# Generated by Django 4.2.1 on 2023-05-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comments_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created',
        ),
    ]
